name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'pnpm'
    - shell: bash
      run: pnpm add -g turbo
    - shell: bash
      run: pnpm install