name: CI

on:
   push:
      branches: ["dev"]
   merge_group:

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
   lint-format:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup
           uses: ./tooling/github/setup

         - name: Lint & format
           run: bun format-lint

   typecheck:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - name: Setup
           uses: ./tooling/github/setup

         - name: Typecheck
           run: bun typecheck
